### PR TITLE
Celerybeat for both perform and cleanup tasks

### PR DESCRIPTION
**Pull request by OmarIthawi**
https://appsembler.atlassian.net/browse/RED-961

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@johnbaldwin @melvinsoft @bryanlandia I'd appreciate it if anyone of you who knows Celerbeat to give this PR a quick pass. I still need to do some clean and probably write some tests anyway. Thank you!

**Comment by OmarIthawi** [comment]
@bryanlandia this is now ready for review. I haven't tested it locally (how?), it would be great if you give it a review.

**Review by melvinsoft — APPROVED** [review]

**Review by bryanlandia — APPROVED** [review]
Thanks @OmarIthawi ! and for changing the schedule to be more frequent.  The only thing I see that could be improved is to make clear that  `COMPLETION_AGGREGATOR_ASYNC_AGGREGATION` and `COMPLETION_AGGREGATOR_ENABLE_CELERY_BEAT` should both be True if `COMPLETION_AGGREGATOR_ENABLE_CELERY_BEAT` is enabled;  otherwise, `singals.completion_updated_handler` will run the aggregation synchronously and we will also run via Celerybeat. 

Not a blocker as long as it's configured correctly.

**Comment by OmarIthawi** [comment]
> Thanks @OmarIthawi ! and for changing the schedule to be more frequent. The only thing I see that could be improved is to make clear that `COMPLETION_AGGREGATOR_ASYNC_AGGREGATION` and `COMPLETION_AGGREGATOR_ENABLE_CELERY_BEAT` should both be True if `COMPLETION_AGGREGATOR_ENABLE_CELERY_BEAT` is enabled; otherwise, `singals.completion_updated_handler` will run the aggregation synchronously and we will also run via Celerybeat.
> 
> Not a blocker as long as it's configured correctly.

Good catch @bryanlandia. I think an exception would do it. Please feel free to merge it.

**Comment by bryanlandia** [comment]
@OmarIthawi Should have done so during first review, but ran tests and the periodic_tasks module threw errors.  I committed a fix (I think this is what we want) to omar/celery-beat https://github.com/appsembler/openedx-completion-aggregator/commit/2f8db6607ae9f4426fa9282b92cbd7eaa683c78a

**Pull request merged**
